# Generated by Django 3.1.5 on 2021-02-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_drink_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-create_at']},
        ),
    ]
