# Generated by Django 3.1.5 on 2021-01-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_drink_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-rating']},
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('C', 'Cocktail'), ('W', 'Wine'), ('B', 'Beer'), ('L', 'Liquor'), ('N', 'Non-Alcoholic')], default='C', max_length=1),
        ),
    ]
