# Generated by Django 3.1.5 on 2021-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('-', '--Please select--'), ('C', 'Cocktail'), ('W', 'Wine'), ('B', 'Beer'), ('L', 'Liquor'), ('N', 'Non-Alcoholic')], default='-', max_length=1),
        ),
    ]
