# Generated by Django 3.1.5 on 2021-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210130_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('-', '--Please select--'), ('Cocktail', 'Cocktail'), ('Wine', 'Wine'), ('Beer', 'Beer'), ('Liquor', 'Liquor'), ('Non-Alcoholic', 'Non-Alcoholic')], default='-', max_length=100),
        ),
    ]
