# Generated by Django 3.1.5 on 2021-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('-', '--Please select--'), ('Cocktail', 'Cocktail'), ('Wine', 'Wine'), ('Beer', 'Beer'), ('Liquor', 'Liquor'), ('Non-Alcoholic', 'Non-Alcoholic')], default=('-', '--Please select--'), max_length=100),
        ),
    ]
